### ISSUE TITLE
NextJS factories sid not unique

### ISSUE THREAD

**Issue by Rastraponovich** [effector/swc-plugin#21] opened 2024-09-25 08:19 UTC
Hello, when used swc + next 14.2, factories not generated unique sid.

maybe i wrong configure config file...

[Here sample ](https://codesandbox.io/p/devbox/69fhx2?file=%2Fnext.config.js%3A20%2C35)

**Comment by kireevmp** [comment] 2024-09-25 16:28
Hey there,
First of all, thanks for a reproduction

The configuration you wrote is in theory correct. The issue, however, arises from how `effector-factorio` handles calls to factories (it doesn't).

The best solution for you is to use a package [`@withease/factories`](https://withease.effector.dev/factories/). You'll need to change your code in two places:

```ts
// in src/factory/factory.ts
import { createFactory } from "@withease/factories"

export const counterFactory = modelFactory(createFactory(creator));
// note additionall `createFactory(creator)`
```

```ts
// in pages/index.tsx
const counterModel1 = invoke(() =>
  Counter.factory.createModel({
    initData: $initData1,
  })
);
// note `invoke` usage here
```

Adding `invoke` lets plugin handle SIDs correctly. With that setup, you can _remove all custom factories_ from your `next.config.js` - `invoke` handles it all.

---

#### Deeper dive:

The following code is _not_ recognized as a _factory_ by the plugin (both SWC and Babel, actually).
```ts
const counterModel = Counter.factory.createModel({ /* ... */ })
```

Because factories must be plain exported functions, and they must not be a property of an object etc.

--- 

Please let me know if that helps resolve your issue 🙏

**Comment by Rastraponovich** [comment] 2024-09-25 17:43
Hello, Your recommendations helps.

It's a pity that you can't get by with just one library (effector-factorio)

 <hr />
That way just copied from effector-factorio docs.

```typescript
const counterModel = Counter.factory.createModel({ /* ... */ })
```

**Comment by kireevmp** [comment] 2024-09-26 12:24
> It's a pity that you can't get by with just one library

Totally agree. We are already moving towards having a single library for that use case, but it may take a bit of time before it's out

Thanks for the feedback

**Closed as completed** 2024-09-26 12:24 UTC
